### PR TITLE
Adding displayPChar feature and custom example

### PR DESCRIPTION
**Pull request by radionerd**
Hi Rob,
In my branch to your library I have added a displayPChar(char* buff) feature, and an example of how to override the character font using a derived class. Maybe you would like to consider my pull request? I have tested the feature on an STM32F103C8T6 Blue Pill hosting 6 digit display.
Thanks

Richard

### CODE REVIEW

**Comment by RobTillaart** [comment]
Good morning, 
Thanks for the PR, I will look at it later today.

**Comment by RobTillaart** [comment]
Your example is STM -specific and breaks the build.

#### Solution I
- Add an **.arduino-ci.yml** file in the example folder and comment all failing platforms - which might be all in fact.

#### Solution II
- Fix the example by moving the STM specific code to a conditional block ```#if defined(STM something)  #else ``` and provide alternative e.g. for AVR if possible. 

Second solution is more work to get it right, but you might not have hardware to test/verify.
So 

#### Furthermore
- Add a note in the example that it has been tested on the **STM32F103C8T6 Blue Pill** only.
- Add a note in the documentation that it has been tested on the **STM32F103C8T6 Blue Pill** only.
- Add the word **experimental** to documentation as that warns future users a bit.

**Comment by RobTillaart** [comment]
What happens when a user uses the **base** class and calls **displayPChar()**?
Will there be an error message? I suppose so, 

At least the readme.md should mention the virtual function and that you need to derive a class to use it.

```cpp
  // Override in your own derived class for custom character translation
  virtual uint8_t asciiTo7Segment ( char c ) ; 
```

**Comment by radionerd** [comment]
Hi Rob, many thanks for the positive response, and apologies for breaking the build. Its a new journey for me. I'll look into the failing tests and commit your suggestions tomorrow as its bedtime here in NZ. The base class should function perfectly when called, the derived class is only required if someone wishes to extend/ modify the base class behaviours, unless I'm missing something. I may provide separate examples to demonstrate. Cheers Richard

**Comment by RobTillaart** [comment]
> The base class should function perfectly when called

Confirmed, as the function is also implemented in the base class so is no problem.

**Comment by radionerd** [comment]
Hi Rob, I finally persuaded github to accept my push due to git newbie issues with https vs ssh. But I have yet to figure out how to enable or view build test results. Fingers crossed. This is what I have just checked into the displayPChar branch:
- Replaced device specific port pin enums with magic numbers to pass build tests. (Maybe more future proof against new cpu's?)
- Added notes: experimental status and tested on STM32 Blue Pill and Arduino.
- Expanded displayPChar() readme documentation and added an example.
- Added serial output to example TM1637_custom.ino for comparison with 7 segment display.

Feel free to come back with comments. Thanks for your time considering this.

**Comment by RobTillaart** [comment]
Looks better, I will merge and publish a new release

**Pull request merged**
